RepoName: LYH-RAIN/quickstart-keycloak
RunCommand: |
  echo "start run command"
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- 80
RuntimeType: LinuxShell
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: SourceCode
ImageId: '"{{resolve:oos:aliyun/services/ecs/images/linux/centos-latest/centos_7_9_x64}}"'
ServiceBuildRegion: ap-southeast-1
RegionId: cn-hangzhou
CustomParameters: ''
Owner: LYH-RAIN
Branch: main
Platform: github
